

CREATE TABLE IF NOT EXISTS Users (
    UUID VARCHAR(36) PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS Travels (
    UUID VARCHAR(36) PRIMARY KEY,
    userUUID VARCHAR(36) NOT NULL,
    Date DATE NOT NULL DEFAULT CURRENT_DATE,
    StartLocation VARCHAR(255) NOT NULL,
    EndLocation VARCHAR(255) NOT NULL,
    Distance FLOAT NOT NULL,
    Duration INT NOT NULL,
    CO2 FLOAT NOT NULL,
    TransportType VARCHAR(255) NOT NULL,
    FOREIGN KEY (userUUID) REFERENCES users(UUID)
);