name: "Build & Deploy"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest # specify the build machine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name : Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hackaton-25-back:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hackaton-25-back:latest


