name: "Build & Deploy"

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "PORT=8080" > .env && echo "DB_FILE_PATH=./db.db" >> .env && echo "URL_OF_API_CO2=http://localhost:8000" >> .env

      - name : Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login ${{secrets.DOCKERHUB_TURL}} -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hackaton-25-back:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_TURL }}/hackaton-25-back:latest




